@startuml 1_1_kaprien.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include <office/Servers/file_server>
!include <office/Concepts/service_application>

sprite $kaprien [499x498/16z] {
xDQ5iTn040N04oxFvX-jsSN6Jz9LzuJmXXwt0000000000000000000000000000000000000000000000000000000000000000opVhVloeTVdcyNnOrcrF
ATNnpVnfV5DJokUshO_dmBBjkRQ8cByLqMivzxldRhRFr5h4_6lHMpwtUsvwrZFtcFyZUZvk5ZlBdkgOBp5QkjEIbtUB-N8nod7zr5cshtc_cf6llU5PZnRp
TKLBrnrr2psF-HP6tIyuwgnxZVbMebzjr5bJZ_cchXQwmEVRw-aYhnnBwlDzHBxRf9lm-wztbkFV0e_lMlcgnNVpNupp8xSx__2bzzu-isyUoWtRG13DzMK1
ylz_6mConvKWGzAIPeHrjpHD3tku9aGelqduHesuw3PLdVSVdSULR5qSQUzqp9Ie2Of83TEyo_9vb7-ULJscvpI4yFv398OfFsTqxv9n6youWhifaZrJk7iR
lOiyRV8sFj7AspHxmZsDtiN35c-Nyntx-LcCtaNQX95dvulcScD-XXkzYoAtE0nw8GXj5mK7kd5TJ2pkyVN3c7cLcqmju74r18vMdZXBHxXR9EB0a5BAlv1B
QS8G8Z_1szoeb_ql252huPEyezmX8lLTkyOvJzDWNmplUHsuFgBBbuCwqRROOlfVi-sSvZ6KtZFrl1fYZKwSGNuJ7NJwo9rggyinf8CRQ30c7g-VS96eEu10
k4e3kw_UA9Dqj7-oQvpdSLvxw31mLWV2tSqz0WYb0sFQP1tlBrxowUmkulMNE6aWJFYZmnvDwB8MtVD9vdtN-4u3RF45C14nBOUWrSZHUPjv5yabguZNjpqL
A2aVYTrYkbl1JWOqeWOZ_ywyjzmRgUvJMBmG3xdP6X7kuG2yc5vYXNdRw4DdNiH-4V3hSsM5SyKR9bHe4OcX7WFs9dCUyuEOzzNJVAAxAWWkqx8mgXYLwmy3
b0fpQKvkvnNcFQJ_yRQfdkcS5-86hwJ9Oc4lNYvuYVPfakc-pFiTVhu1uj1Al30Y1SAMcfmTLiA-jOyC_lrD_iB4-KhWryyj1LwmEYsbcZWGg5CPgZUvGpOk
hTHhjSRhqL9EAGtuekdhUEtwceWykCRsQcgOMC3L01Y_1ts9BSTgP_wXdPTucYTuoCzv1Z6pUMktFEcv60IxnNOsm4KBS2dilMPl2YyFyuNCkyLp6aE5Q3CX
i67Arn8lCiWRTYS9XAeZJ0mrbTD0C1NSWaruElrs6kNrB3vTksjCOfZpfSJ9Wofs1L21wtAF2qhlJKfo5zjT7lejd4tyMi0vSfltF3eVsZRDrssMCko6NH45
khxtsaaTS5YvpMc9x4tHyFBpSvd-QhUS55E-Q7-yc9YZbcBYAF8AF03Zyc35hILdF-JpU27YbjgxnkViMPduUGjLc9MiGWpgG1Xhm8thUVXunZ7csLy5E24V
sJM-lspni48ysE61fHEp8B_5WOFCP-dl85bsZPyFkO4zk62dZwZ_4VeFC7-T54xdDl1dGnwBoyM3ggs_8gz9tc7ce1SWdfuV-285LyOLEIn07xdQHs2NqBqt
slI27HcoDUB_iNST2ehaEX05gqJy_xzzeItlCE4Gnj1SUyUNRtTILokNoci1JlLqfsy2zvyWbvr21zxtCq-EkBzPRu7jq2vGu3kBDBUABAdPDyTkgD5-0FCz
_PM8dyfAW5yrQev6UR_8TlHHUXFjla3Ei6Z5t7lqybSDKib7I2lZfvmkdTG9GmtcsihyPj91WjA0VU0PJDri9_mJXO7UrFyvQnxC5qZ9t9MhRKiZGXanmjNt
dFtVaxKJae7sweZdcBCRxSgIfvb3csCdDJUf_q7MwQFazBTaxOGiYgzV7EQOcqjm6adT8L6LOO5VtEXZTZeGpa_y5yNnFQ_LyekIkBFznHLLS7FcvcR1U6H0
miX7nIryIiHNTkhvy3BEFWa7YrT7JShREAt-1x0KvhRhFeV4sKnnx5txMRd0WAMavWLpfG0T4ZDQr_ZbxiFVWio1_eekwt6zLvlFZwguX1ahuY8yObe03-ZD
zJble4wD-Ff393hUvBdJRJAKQmHo564Y8YdcNZZUXu4uCw-Py-dDp2zFcEwKkFPQYXiS3i0TA2sSFuYKdB-resP2dFPlHhnaNFUIRQNHXtI8cJLj0JQNWUHY
ul6AhvkgvxsFlfRdboKa-kBo1sBDd4IuiB5rlLXEJBWhacROge_eTEgyPYu_f6vuhvEfGd8TlP0VFRYuyL2uczNC-PZPrFfE1kWDv-pWv7-DnviJpG4v7idS
M8h1O5QKwUaL-Pvetn_El-Jc19VHHpDdRQwNxXqDKdC7O9L13AKHnBy7yXD7sTZrRQaN-howf4-lNGyqPqL-f5nXpPGNVXgn5dSKVgAJkMYyYfsXrBnSXmil
u_ZOZ4FKVU-qKioRMTE7qPlIivnCAnPm-U5ToDBsD5d_DNCzTwP9wYXB8rkBMGlbfEw5dfGxxXk2Ftlyl0iNoJgz8j6vyDOHfsCVjO_KJIAOEm0qWRMs8pBU
zZjAyZhSE09mSqNychZdKxNTSW8lbQQmvgRCEo9MWqFhB_LZVhiMwm_duaP9dtKmcfzedYPC_XD5WAJIl3ZpjLRg0vZh-NR7nNiJZVWEpVLvwUrKTHfrSJ-Y
cyLsfR1ME5fVu9XC3rRa1qeBk8mZKxXuUPqZt4_MMqUI4VEEh9euwHN7ZDJ1zTSx3kNj5kbU7I5pkD7h-XPddih8ZvIIp8gNJmfhKR7f0rHIkwEfMhfNHyZS
-9M3PPkbqvgtD1b6KUwoeIgiGU5kKXrg9HYFiDOzzwlvlGYizDBsv64x2EUH5EbU205SypNHPkVcCAw_mcuZ5Vc1yZ9oVKuvdQRPLa8lmmoyK144RXyAQuLf
SVABLoS3FpuZFqaopdfJ2mopU7O-zxKpsMs1bCpTh2afIjFAvP1UqiS3kIL9vhjOQ7APfEcApbHONQf4Bk3khfyKrZpWPjZ3ypiat-dxzWYES-JiTEvSg6rR
lMGGNuvHQ2WMCUVc1cXyVfUFLu_yJklGIMfofBKFxGoyOEzMfP1PhGvEpRd2RKwFDNhFtDMoSNgZPz_FK9FdQJ31Q6UW9Px310x7WdiJPbhWBiwFKP-iStcf
lD6pdtXk8uz3rjmsm6uCOtLN3amgv1oGztEOzpJGfrlRirysMQOTUWT412DgLkwsYETz16v3WnpIxs5okw4azg_isJ53XMOfJi1k1z3ISt6e1-JNLevmxFrQ
BFg8JjEQtPZjwuYWlw5bLjCtCf2vNwVd4Sk1IF3QUMQTRM-LuFF49swG38DxrLAr6hFQTojd94LQEXpxzuPpstnbRfV-jrQzDLMNUfpfA-JgcZJPXthc_Cx6
Ar_6weNtdts_aLUug-yM2g11LtiXqQlfNqRIXoaqU5imts3orl_GgQaWgxlnDUHKt6qdTzrLP0FIYRWyJo2VMAsU8apTHdAaZHVb-wwxYdOSBJS2Wj1ieSF5
i850dfwdXNCEXgxLUO4fzmPpsfnVxuzCGP4eIx2ENGK3aQ09x5dmPZevpDn9UX_cAuJ2Y38JVN1qgQiol-WM_Ng_bpAN88y6ImBG9iaY3iwrKf45yl7vMtu4
NtThME6GhkHHD-ZN-tEHYYW3Maq5rmfh3gskltiPgUlOs3iJYOVIzReDKNs5bP9svORxR_xWGwCIEch1OZTt-wEm9lbI49_7_V9-a1OLPCWOydzUjocKGBvP
0XoT7iq-2P0ATHLOaoQkjq1F08ytKqOREJdYL3NYwkuirqnEQ4UtCRTDGZu-8n0tYa1UX2YAdGZdvZeGo5S9vrHYcGKrHsTkCQfKp6z4mostN6tWkQkNFu4S
C3EumxYj1erpcFFZ0ytsvNjak0NKiHWV6pXaBecXR6r-EZuY-7Wg9CK0m4hKj0BZ5VgbsUWrLtjbj7KR-9_oZE9b02VXS9EGqsaaAbq_bUjxZXWk0npcmN1-
e9ugioolhBbBxSX8S_dXn7uyjE4gJSOc1EAWHC2XOwkuuuopdFa3LQaqV7XHk1l7Jq3cd42-lIfjV0weCCerzSOhykU_FxKb35fI4LDjbzp3lN3z5V5oPppq
xNPRZxlqv0OjRZJAOHuNaSfBp7eBYtXTj_6wNnNhDfMn3L1YAXk4V7WCI73z8S1dhzcWSnbVMfA0bE1UpBs8keEZ8mUYEaEGwI2dKyVeCb7XILAt0HBJ02iw
fVKGlAxRmAsjsy2zmYsk6uSypzxaaS_XnXsfcvwUpsruW39fgAYIc_foIlILK5eWlp7-jSrCpCUxI8a2CcKo7NGS2EJzdpJVlO09pDnTYHM0ngODkTq8vdBP
wiJSa-ojet7v0NzlQrrV8bYtf_HsL5Ha1KKSS8Hl3yXXDpQi-BnLnkCX8SJqfktge5THdxeJX1HojyNSnOjuONNNQnfVNQhZAI4VV_gHikN9khvgXP0wYPEy
q3LjzyVATKVDGJN8VKOhvtFIU-jBsnaPcwINmpn6Y-BKiUyYbjVSFI0F_dr4-yaWbykpsFy2C9dh2Wp5Zct6EvRgTcvixjyX9vyIShuyRUohZXHn6soqFlEp
HwIksAijaEEQiItX-gUryl59VoxFBAVXGDxDiybRCMxBA8skhHo8LWpAR93ZcUGEBTGHRSSKFyOpXT2o8KAistn0JkAW1NPrcGZozUT1_d9T7-cuQQc6QfTT
SIzy3JcRBriufS8-D-HOzzQMYxsEe9rNQkPjHDh4h61_EFb4m9LVpo6dZK9kwzvLl7_XB3XdsyJMd5QK8LGJkS2_UBafF2o_LZx6KNj-ECzPpWHmwnjIPSH0
pVrQTzZkxVQTw1VomQtY_8pl80iAxQJr3SsNOnpEdKDs-C7XwI_aPO1l_YAMStXrGTIMShrk0ubLokaWFwuKopdH-Nfj13dpBNwkM9kVgJHwCtZvLPeFSZgl
O-Kym64UQBocvR-wDUAJyh9_IDp2ETrMaySlvBSEZN2ONxgq52rYhcisPlQXK9c8dXn_8Nz781-VdLCR_R6Q0VMUtXzOkkcsYcuLyl5Olgfg_lWkpFKY5H4J
NG-3EvZ15zuglnLRgyZ7DzxKBLctwLX3_2tI1YhomLFkhixfnokFqp6m3l3mfuTSLmZa8zlhPAwvwUUI0hyzzgG3sdt6P-SdIbSlxhy7UPz0ldah9nPTZj0J
Q0kyAgilVzK4u6J1AgE9-boG4nVpTc1A2Um37EONpr4jNxq8jcwU7svMzmtvD5FC0LCHPb4rTnGUkwjuXTEfyrxSacHz6gc_V0J8vcvNxZmQajmHo5UOCexo
hiXGRcJmYGk9edCIkgEu6_y9vY9CLMG3_6ILrPNcg7lArssCvjNWpqdDwj2gS0clf-xZ5eUieQNyV9Qp9HlJuiPpYtFppPYaRXo-tLH4j5ZSLYrm6I0VhdNy
VYyZS8w_zvS3jc4zgF8DSIhku6MEl6l3P4cUpVht8epVwK3Ync7hwIbRlZNhyC-GI-ZTMH07pAI1hb7CzcRCyhvS9L-MK0UW_TuZwAqJB1kJcoo8SsC9uR_i
dOcQcpeCXQt5ai10tlzjRsE7qLTk61e7naw_dYwpht-EvKMMB9RdCtCsEVNsR_DpMuXcyUnQUVqlpDFlTPZNMW4OpOHBfOKor-6Zh16go65k7Cw16QfszZJq
fSeJ8LA1Hu40O7sKoOfcIf2P7rJOXx5LlyBZ7Am1Jqx1uD2tZizzlNMA6fPb-1suHX8pCo5O-sXGeyj8nwglHlJtDp3VgIa0ghaGizUwBFKFARyC84e1JVxy
l7hHTbtWJfvKu2StizvFsoiLi4eXF5u7TdtimvW0URca1e6yxM6UrBGVwhysjz--pc9QA-jZD3E5eDxvhbqEi-i7wuU6iM9LtdC5VlpzJZsQb1vY9YjmOHLO
6s2Utr2X-yGSd3-woIsWFlrTWCbQC2MIcPQPEfTZDL3nseUdLSl-uIndEU-J3UFmIyBKFtjaIzCMp-0bihGWPsCsCurYAbJkONljmmORhMsJR27TdcfPbZH8
pzXHnjbnRpSFIOk7iylpNrO_EC_8LSBpUabMyUjj4Cw7KwB4LlCe5BeKsNJR4HUNSq6EsULKNlJYEINQFqLESrU1V3_Oq9lptNtg3Fq17-RRhko9oxbKDFQI
QP2vmpFaMfFirYBBMMidRuTQKWnT2VJRxpfvB1S8g6NwndVulatZrH6tWcad4wMrXdCMQdBx4or3Hqw7k67oRC1p3uD58B6rFbhHTpDsc1i4yYfxBdZ-kEvQ
54CVmc6v7IFt0lLeiRIs_Ctb0i166VlERgHByHkTlkRyHleZo5s9GtFv6SCnyfMeLozsbvUDMCKGbOvZvloTHZcHEkemVwEbOevHWTor67Gmg1_CFVmuEUCk
bNYbS5rT3YmcWKpsPc-lAGcU1No-lIQz67dx_OW0jjoEDNYyPkFI2HGSUQcB1s8OoEBXQUonbdEstpdT3dJEAetdbvXJO-At8_aYUcqJHW4oPBmZzrQmRD7J
OhQn_5NDz0CHotKSou4U_UiZ8npC_0yqS_SUNzG3DZno6e4pT1DaBJjmj9yL0zEjWda3uhl78HJjBYaDx7Mxsi9KmRnFZpjnjtbWBtsdPgNRp9h5BiRLmUxa
XHnL4D_9gISnqqW8To6BcZ6-mtp2zhaX-ve7tbovXMY2wzqqx_Ii7BpQPNqmTmtd9a6y4C6UNC5322uWtJeT92tjvt3riuvb6Yq-XF-_WWjn_O59Oe4VCt5G
nODJgukdKYwvLMXyVcL5q8Dv2UN0Kbxh0eeRoPZctSSpD3z9SYr96U7xVlJvKOxv5VckkPdGjzLKUFvfcv_r86CrXW2bd6iEvMMoYivyNq0opi-_b3G_BtRW
4VwWcIb6DPF8p574JBoIyOwqWi2CPssbrY_AsPGUOti9viXHpHWylXrHLxTMupiRKW4yEDSyYxbBBJBufRqJG-l2Fpkk3x3JkdLTb0J0huqdyb_5aT2UFVuI
jajMTys2uL3UlnIHolLo7_Ft1SDIwxeBDyJscsFwc0Pbek81VBrPxQrSZyHZnKztkeRQFNyGuuDNFrUSAfPC5QeB95E4dPyfck9NjPIrH0fdvc9Klm4oKtEJ
Z_XAOylNow85rEd7aDkBm1M3QtCXIt1Tgd4iozB27BnMzx7YqdYb1bP9t0FS_klsXT66DEzhkGhvCkzh6WR6dMenMBOY_0gUnhKeFriC8Hg_qzMdWSahYBkZ
NogBvWB0NTbLoAtcW9xkKCKe0r-lu4KpiSSjU_8DvYhcOuD8Na4yQriX2TGud22zAfPhg53C9uC2A6hCqLIej5KgT_3oi1yDApOx6znLfFczB-vpDN-nB-Js
Fd9GxvCdqQ_WPV-RKH1F0ghS0zO6Q_BQlI0KeqrLl3CaFI6dzQg6c9fPfFYOhcD-HS4DAb2_tpbXWm90LJk-lWldeVtlSpcl9XPZBLVmwB5M4uv6Qze-lf4v
7rjTmLkehZVvvhc_B9P7nOmzH4CrCJD1MBjeiL78kAFH6tEeeLNAleMNvTucz_lVut9FwCMCN1JLr7IzWlVrMCZFl6AsHXEuyPHje6WHFAh_TR4Srlxrz_zK
KRGa0Fced_zx3JaCRPRcE9qoke1ON9Td3LnEz2F88ICNnNL9ja5Enk_4L6aJoZdKCxzZRu9SKzAhOhaZZrykPvMmHHutBk-tF9oSjL90COlG13cDKqfqRInV
8xKOHZFpwNb5B6zJp_dy7Y3hVcE3MAufJSakNwInyHqv0Cd_1tOV1roNLsrltySMGcZXSXfJIjD8rsx5S42JOlS0XDk1FITtgi9xTR1R8EVGIlN8BKttFmON
8aSJU2ozsMjY-UvZneuMuOGws1SBvez77kyUl_-J2v5dt6mniAudmrAGGtuDg4B6_fh61iXfQLrwiZwM-zoj_4bq4NA_ZsLOgbd2byjHSjPhp6zMU0-vD40-
XSznkGVoAQccNnhfEkIP9sMevQv2HevIJbV8j1HH-02NymOvV1XopXuV0Ep-TEHBrkLkysZngp9rD8gF7JZKCcV7SwhTx-kVoq4ASGm1XnpH1IvmkTiS93FF
gVjt2NsLdy-H_XEHmmV5Sk0XPMzZ25_CXmZN82z8KTRKVR6lcrcPk6SxTZwmO-NqhRtBCTw1tprEwpegfVnon4kGWoXbr2jfzYjuu1UokaSEqoSkqf2YZPbt
IWO-zARokj4Y8PmSoyDl-Qq4aBCrAPe9-l7n1SZ_RSMG3iEOoUOzjnY2AwwFWocDmw1yfiiTQmxaAX95TBs2XrMf8JXtW7peFPRZM9ZcFqbnQyJnyRRiTZeL
kG_UI57ks5KYmMDkHoUaatEBOvK4dRkS2irCL2cu7FeqhVjnPoC7lvi3W0ZWZuKgWqg3TcerVVlQ8y-JD6NSuS8wFBpEvo7tnCxT4V_jK9wQDCMwwISW5qRu
rer8ab8w5_a-NBAAGDwkdHhClOxiiejyn70ek1lzTEH-DsTh_Hh5HXMhjpbtiNUN_zAV8gVpaOCOFmdmDOBKAAZAKc7pfiYdLrsk9o7tq_5JBcJ59hzv3oYk
-BUu_FnOxkFuVdIlhy-ZpIe3kOVQIcfS3k38fmkGEsH_0S-vCp9Jkz90zhakbt6K2rtkc7Sdw_KNVbFBRWFnKsDvtcJ72rs-lLsBfdHMQorjsS5xmizqkUGz
EJnokOHt1QBia_Ng5jhjpgrfhc3ULIntubFIYsEvJzFp_wULLjJ6ZVeJVfJBtUD98MJX-LinssaxIFLaVLZQkioZkMlYJf7ZNYgh5e-l332bAT5bo0EfrXCV
szVwqsUbPA5xvC0HddZSHmCwFPQxs4oXkkL7yr0AKtzjFuBi8F-AqQ0fPpfw7BVCm6F-1IvtiLHX0btEhL1xPclMUQ2kNEunElgp0sv7zQBeCNy7UHE1f5wg
y0yLRHgR88SXfQIFPzUCPabtAGINJ6aQO6UFlPKmJaitlJPWtEkvO141ka3kDui7Tt9A0taSTvdVF-x1vG0OupXtrL67vjkUvcaQvESrFaSkvS3SqnlJk8xg
suCqUOvybATYVDuguLLjSgg1HKIdQRxjIa9enRnZEN9QqrsS-TRZs_UoFsp15yDMCIstLxNC0k5BT5nwtY0q4asz8_S8hfx6dDpZcrNw22_MOrziIznjK5d0
NwQQ_WvP_vYRqqmFckxphL7ouyBWrNhiYxpLzyUbFdJM4lytjZjoJhyKGt3cM-9bLUxlOtLjwY3TgkGJCXZhYV_pkIE7kwyjV8aamhE2GICS83-QIV7Rtoqj
Vn026el6_f47zJtNxofBQAX0FkxiLTJrIzKZuX52Su4jtIEdqSz8dqjzWxqUEKnl8xU3T-BGXMBg7JcOxv_lcNnAGtZNvUbMh_aO-J9Ww4JOfz5jKn_6u7kJ
yzl8zIsN7xKEJZ7q8-2qT8qSBEMpbHt5KWMkXjsYcpppMWq7qxSa6BeInFwWstRatXlQCP-sK73PA-Oy9PWlzEqCS188tGd8fdwH1ycNJo4y4MZQpkxifUMq
YvShjcBcKJ3qAOp3t2jo69phinIu0MgGpzjO8PKRhhgxWJSdfT2pa6L8ox9qXTndSAFi1F94uNNayyXFvlu7F_jXHsYofRnsMQRHc21yW8X8h86cNUIU-HJ3
Hfpkal0TycJF9C_THz5Uaswf8kVFJhtJxhy8c3vX3l4-hvl-O-y-a1k6OIY8WjqYAEd-fqr7Ua_eeUXzLzZvWJM5AUuNZu2DZUJsfQOlcoUzTN8oMtAIM_Fs
ufwxhDfKJrxcJ4vostbnzdLcnG-Q7FcBvBPpBVxPUvvMVBRahFp5i9SWuXTxtdFcv2Itt-qrXAMf_LP_eqoKdEIIzLQjBrvZdtBbt7AJQcjt2xSFjccJit8J
gwhQVzcOEZd9JLZkYWSnizzoaaiuQLki-EGhvvQ_ULjW_kIit92SvAFVSh1oP99tmyh1BGSh1xSSh1pSSh1oSCl1ollZbeELWriELWwIZu_aMSuFt7BmXnry
bvDy2RzMZvMSMswsNzkFafoLTp1sSbRUnnPbJ0ZRtiNgPKnmwzw53fiSowMTSgIjooaFCYgukdUWJeQ5s67cQvI1eVnxywt8q50epiwdBuwyxl-cHJa0-DAs
VrbuArwE0JvcRN-aEJev4BY_adC0000000000000000000000C2dKahoSYcGgcfJhLak0_nTyQQgGSu8Ffjhzir4oLeL1i86P4ju_-UzTVXZYprhdUrkP6eM
aJ5LqtvsWap0c6GQV4cac-93zRTYlYBPd-YMC5RiKAF9wpBdVcGfsnjZ1LYpX27jlOzHYw_CtCq_tYhvYWIYq-cnFcRvbPaZykpR6sF53jPSSgdWlifBKsVF
_6x85-MkhoLWxvfhV77kM5fhvUsCByclb4SzZYsz8RriVtCiBvTgtO_B-nHwVvxbvQZOCnZNS1KXfbngQwrLMYEDQHyVCgQbSfknovmYZVF7Ea1jhUvZwexV
d492AdMaoL4-oHFzeDpcvFjSOL5-UddKWtcKqIwaMWV_fYLkY6BTZl8-DU_ospwlik62aXKLMxHk7rl1lPf7Dsivp7b6DDcsMCTbnk4zzhCaXvUFQlrZVvOK
x7UVhUcKmiyqsV8vJpCajsxUVOVZ-cb8Vbplb3nKpu0y-vd7n-EsgnaoMRd71LR5xbwUmNYJIpU5SNnQcgHmZBDVY_lyFySgKkULlXtNWgonpJdetgi-LgBE
Sp3Zbx5Y1xlfuAvpVnPcga1X9CfDBtns3GVbFfhAXMjaiuWyy-_pgc31_6kUkzO8ruDzA29WZC4fOvm-Aw_8ysS6vTxduzmGQSVS7HnZnlIJ1ZxBdtN9U8Va
tNegg9igJOhg7BUPzqYKCvyQuELCRfWeXvVlk8ArMXNp2-KneumQbevtIDwjgfrS8K2ObZsAI3fPJJW7tlGc5OuJA2SkLJxpychmRzasoSUjei9vnZrX7STt
j6hBoo_qv8qZdftsZlb4dqiLAhosEEN4f1U7xEK13kqrUC5JWBsynMqJtApzlW9kKTv_wOs2UhcmbrU12pYU1-NWjwOOOnfKifTdt1LnBlLnRrNCr-Y9_VZU
5pDBSh3e6d2810aXwa5RPShzITzGzmVoyaiZm5vUZkmgijq-mf6fKirG9kz_Q8_5aXoSL-5fOS-rgUhafv0SOn43M5QRAETRQJURlNpg5vg7TJy-AVSQWUh2
EoHVNavrS68hr-ayKywhyXcL_txrw2RRrvIBVbcHD_Boyy7_w1ltHJdrmXxY7FDdnQeOwd3QMxNFbBCoEzqPwappfvbUlHnhFFg0bw_tvSnNtX37CYdF0UK6
3sRAqqGvhumovO4fDnmtkL2kyYJA5-LjFmycp3CnPnrUFgzza-HZZ2Y7vEJbFWrUpPzAUK3vsJlS4wilBpA0xlHN30hsjAGOOhF-avVxY6k9PyHlAKUCdq5v
VpBbY_84yhn6uWajdfKrl1m5-hG22pxZ2UFNb7TKxDupj4WHoCknGj0VzV8bELOrmJ3MmD0RIMClvpsopUUZBwVpN_JbzJXkswV1bADllr_o9Jbq07lCB5RV
k2_lvmCusWWS1nn_Ixc_h4T_pm7AX-IW_54lN_lOyOT55uq1Yt1gfXmx9CSQkvzt-23v3rw-HPI7BSpJidnD-UDUlYZVeg8sJwHezVTREAQ-76_Ipdqnl_Lo
DtFKvBvtKc9kPe4ftqx97_Fo9JbXhdBjiarRLGF3H3dtqtW01un_JJdsP25NQxNft9F9XxvSdaFvaZm2IYjGXZvvZNq4necz7_fosXLZdESJokLPVVdoSlPc
ZPSAtSxldRsS6JVU-_QZbsFDbQy5ob_Jbw__IGFcQ7xuNLlETktBeHBURE5wl_Tox73jjDPd-WNbT_RbAtQRAUVdQuIcK39lmOLXBwy9uc8V-yzUpllOhTDJ
HGK6ykoAVL7Ec7jdBLanITEvhvtxyYgneUR6rQX9-ufoZ5Qzhg_N_Pk-_0ulNn7A4H5Z2MCvU6_Sr5HRzUOfZvE9A6-oIQggglZ78f-D39mvZyzm7H-RCUoM
hvLqdjjzVi6TWmlls_DZXGGH7YFADM3Yeo4IS9r_NAoWIlg_72kOyYNvN-tJ1G60C000C1pw5yOZtBzrM6IMOpcMOpcMOpcMOpdhyTk7d000000000000000
00000000000k
}

AddPersonTag("users", $sprite="osa_user_large_group", $legendText="aggregated user")

AddRelTag("validate", $textColor="orange", $lineColor="Blue", $lineStyle = DashedLine())
AddRelTag("download", $textColor="blue", $lineColor="Blue")
AddRelTag("fetch", $textColor="$ARROW_COLOR", $lineColor="$ARROW_COLOR", $sprite="service_application,scale=0.75,color=#438DD5", $legendText="Fetch")

AddContainerTag("files", $sprite="file_server", $legendText="file server container")
AddContainerTag("tuf_updater", $sprite="service_application,scale=0.5,color=#000000", $legendText="TUF Updater")
AddContainerTag("ci_cd", $sprite="service_application,scale=1.4", $legendText="CI/CD")
AddContainerTag("kaprien", $sprite="kaprien,scale=0.3", $legendText="Kaprien")

Person(users, "Users", $tags="users") #Green
Person(developers, "Developers", $tags="users") #Grey

System_Boundary(build_systems, "Build System") {
    Container(kaprien, "Signed Metadata", "TUF Server", $tags=kaprien)
    Container(ci_cd, "CI/CD, Artifact Systems, Distribution Platform", "Jenkins, Github Action, Gitlab, CircleCI, JFrog Artifactory, Custom Solution, etc", $tags=ci_cd) #Grey
}

Container(files_repository, "Repository Files", "Metadata and Artifacts", "HTTPS, FTP , JFrog Artifactory, NPN, etc", $tags=files) #Grey


Rel_L(developers, ci_cd, "New Release")
Rel_L(ci_cd, kaprien, "API")
Rel(ci_cd, files_repository, "Upload file")
Rel(kaprien, files_repository, "Upload Metadata")
Rel_U(users, files_repository, "Download/Update/Install", "Verify & Fetch", $tags="fetch")


HIDE_STEREOTYPE()
@enduml