@startuml 1_1_trs.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include <office/Servers/file_server>
!include <office/Concepts/service_application>

sprite $trs [125x125/16z] {
xPY7Ol8miaQ_QMfMUV-tlOmT8kFW07_BtLrEUYHyD1fLy9Tvy-RDcpTlthnvy-RD6n8DCUMSOb0c_4FOyhWX6-FVeEMYwxMsxjxUQktkL_nzh8xHwkQjotBz
hOrH_xPUbZ5SD9894m4W5al36pJ68lXxKBn8BkeaT2ZGl9N4FoWJYwdaajCwfBbk0iOU8ZYyDMpXFpIaozZJKX-jZypO8oeg7_eoUXj3yDj8Tf-FQAUtDT6N
BpjqjuYmA6F5nlW3TYbk7ivIBhZPExKnRd1pK1ObhCYq_-wuwkcwU15BA6CKmZ5mYwQcmjYWnUsCN-KwheeUL2mumCeX6BE8O6-lX9UPNTT74Jp4vUhUdHpK
BlQ4NqFdk7e8gGW9YGhZ4_Onhx_excrKnYcSbiJuG2wONA2RHxJH2AyZxixqZNiuLpi9UzZCs9Ckze2N8U_pZ7CyesqN63C89CUdz3u8hv8lxe8DbWiCV0bg
x4UK4A0u44PzFNJrHzFdkdb11NlCqwcNhpaYbTp_9VHHwHSwNR32Aco1MHbV1hBwNEHf1-w5BdW96tL4R8Xe36egWa-eZhPMY8yM4lQAhmO-nucoHXCMrYbn
vm9dURIGbF5Ylzj-cEWwXo0ovREt7oyaORJNLlYo2zojp4mgSaZuiI4Jsirt6VMbLOvlkf95M9LtassPUPmfs24geifOeHUJRhUDbMsUozvMCQc7ntjTzSzh
ySXu7by_29-G00IXatu-ffrL90GLaUjoDHOypp96EMxVmdkLOO_TD4T4Kn0nKVe8PLGymLcMX6Ud5nyGTxggJBa4KtokIcdqJY-DDyCDSfFmHdSscRaeNM26
pCXVs5jE9ySnuITfPtVhF51vjxycbs_MVCDNRByHyNQku2d77v3l4twUTX9YPfAvlXRyGhSJ4VQ4GyAFQG_Nq36tTkhzbLCaVyX9L5LutwhM3drolr1eRg_y
sacAjkgamkjQTPxmyxJFL-bhQplvrVVZ0cGyDxFyu5ItB-UJvV8nViF-k039F4I46TatKo7SEKUzCjw2xnHCoZOlG8U4FqZxyUXUSf1dt-rOLs-Q5w3Ji2Qd
dPDzLNAMn_gmtael66ulG64cz47Q0_RJD0t77_f4qxrMpJaSBq1vz97ZIc0SuH1NrbghMdHhDgLyeRf-sizNxYoV2vN8vmKeUj4L-PBiAzqtc3lJLFAZinxr
cxnkMjdTpFhAF3NjpbLzvNfxKs6Tq_J1P9d7fuI9CA1p9FQsqkSMkPjEry8Yss4cH1MxMH_JgCDmIZu-LbXevrXPTtIwS_gW5JWi789-JjFPn8mJZbl0-GNe
AgU5zklnX4LK13JbvqUQrxQ0AGyztfUJYdnSs0-BFtydj-Vbb99_tfFFQOedv3Drpyf3hWR0QWu7-Poc98p972ndH-RwhBmADgJHbDzEKnBigTyUuCFSUX_A
2rO8AFVa40OfzkYyVPubVV2JSi85xeJbhXp2UdZuQSfdLeO-8tUbWhk05joLGmvnFnfHrDnUJBvZkmGKnXAh0EpoFf8ul8ss7Go0rSfu_9OSTzzz7j1T7WoK
1O35xOsC3LqZs6EmZpsrCxw7qlgM-dTiQpjNR2oyhUtL6HcGiTJ9ACXZVRC-4HuYwQd84GES4E7oVUJr4BdwZoHu2c8vHxUSkqC1Q2NCdEinvzj_M9ZmHvZB
QpLOdSlhFs3AGRbcme_87GD-Jex_VlbR_fOBxP5_Ap_IXk6V8ADzPJ3-LUXV2VXNi8LRZF7VpnlwGozHXzW8_gKNFluhE8Lwm2bY9lX2QdVir5fldKDds13g
hNajwgtsY5DCG9Ln3-sbrNjDmZsa6-1oxOos6Qa5v4QmfHguM2uCIZKBA9Kgb9LohGOjDG3PGWg5a1A0s0JabOl0efRWFnUs18JI359gf9rSF-NKikagJreJ
j9jsuPwjHwIckSEwAL4FTD4ozsZTiBHgqcLBXlPgGEeIlNADt29AGUhG7aoeH-dXAATLNfUQNLvhhuJOKkh6NL4ohurXxZN0DTO9rXarKIu4rA2TSK5oJrIM
M3fR5o0MDwHAqHEgFQUUZtBnw6bsktP5wCP2tEqYfvfM6OSUNBxrbRYyP01MrnyW83NEHLZM-f1s4ICj5pcxBOZ8RSwvjz8pgATDxjtiOIPBn7qfgosr1PP2
Do-slXYr9NL5Mm1mxOeBfQNkpGmM4LoEqYEGEwIN4gXMYrFEGTRlqGWK58x_vFKh1d0F5WXGhy4nsbfC8OgN2s2scqpY3_BAKI61rlymeEQ_10PPZ8odyPm_
nBE15_YZSksHVd0nVVFcpPitR_uF
}

AddPersonTag("users", $sprite="osa_user_large_group", $legendText="aggregated user")

AddRelTag("validate", $textColor="orange", $lineColor="Blue", $lineStyle = DashedLine())
AddRelTag("download", $textColor="blue", $lineColor="Blue")
AddRelTag("fetch", $textColor="$ARROW_COLOR", $lineColor="$ARROW_COLOR", $sprite="service_application,scale=0.75,color=#438DD5", $legendText="Fetch")

AddContainerTag("files", $sprite="file_server", $legendText="file server container")
AddContainerTag("tuf_updater", $sprite="service_application,scale=0.5,color=#000000", $legendText="TUF Updater")
AddContainerTag("ci_cd", $sprite="service_application,scale=1.4", $legendText="CI/CD")
AddContainerTag("trs", $sprite="trs,scale=1.0", $legendText="TUF Repository Service ")

Person(users, "Users", $tags="users") #Green
Person(developers, "Developers", $tags="users") #Grey

System_Boundary(build_systems, "Build System") {
    Container(trs, "Signed Metadata", "TUF Server", $tags=trs)
    Container(ci_cd, "CI/CD, Artifact Systems, Distribution Platform", "Jenkins, Github Action, Gitlab, CircleCI, JFrog Artifactory, Custom Solution, etc", $tags=ci_cd) #Grey
}

Container(files_repository, "Repository Files", "Metadata and Artifacts", "HTTPS, FTP , JFrog Artifactory, NPN, etc", $tags=files) #Grey


Rel_L(developers, ci_cd, "New Release")
Rel_L(ci_cd, trs, "API")
Rel(ci_cd, files_repository, "Upload file")
Rel(trs, files_repository, "Upload Metadata")
Rel_U(users, files_repository, "Download/Update/Install", "Verify & Fetch", $tags="fetch")


HIDE_STEREOTYPE()
@enduml