@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

AddRelTag("validate", $textColor="orange", $lineColor="Blue", $lineStyle = DashedLine())
AddRelTag("download", $textColor="orange", $lineColor="Blue")


Person(user, "API User")  #Grey

System(kaprien_cli, "KAPRIEN-CLI", "Command Line Interface")
System(kaprien_rest_api, "KAPRIEN-REST-API", "HTTP Rest API") #LightBlue

Rel_D(user, kaprien_cli, "Command Line")
Rel_D(kaprien_cli, kaprien_rest_api, "HTTP")


HIDE_STEREOTYPE()
@enduml