@startuml
sprite $rstuf [81x129/16z] {
xTZfbgEu4WJWGhb6flhzN_UIoFWOWuPgvjn_4xtHkFHP8U7L___vBq1aPb-J6O5_YSKgXQkmm5dK43qBVQn1QVbPqupPMXqjR2kAHro4h5g5LcoX4eSUcO6_
vLoDNrxpEbX8Tr5KCI6d79Fktk83MbZtCo9Kv6-zXD3BgmY_3jh7aH3PBpSzmgYHoEurgwDngClxY5jZvBs82ANMHDgk6FtiMPZtGwgV8ikuzI2jDTPIlYTO
pFi_BAlODEBEuzRQle2LEhoQugBSraZ4hRUy2rUylBT2yZ5RkXNBMvP6GZ_dVHYABEzZaI5cJBsGLg1yZk83sFZplgXLTBRNI6s72LQiobyiOaLuY9xNO3Yr
PGLPbW-mZW-TVqvJfEjbHF0smNeyt88ZocsBN9PEMxsVhyRB6QmJnsrfXBoQ80rGFeSq_GPvENTkd9XDiC2h2ItBo-3FNR8NI8Zp5dE1tql8l9uZTQmnQJEm
IVy60-LzBs61vDdxdpKzGziH56uZ5FXkh1DGehHNEkG0Ck-TJzTYvnV8LQoohFaXpq7jObghMtPGTb2_EYFR0LpO8pFXDRr3ecweyliJn0X_WH6jRT00c-LO
jY-lqbzJbUK09ewWVuBDpz0PNaMM7IJ475oil7kHbm_Gu_ko7W_ascN9hw7fAehpSZRXDWVtYFhNE6dZtZI_H36QWU7lMyIFuxm63PBY208qNKDiPqaCSTpQ
3fYyndsBFU76D7Rv22BgfELi_I6qYNAnNI5qlcoGr3Ykg3V91JQ_kZ-dquNjdSix1pcyteDMiAPu4P1-WscuB6kvUMQPsnIlxtRLuWkCoV8viWQGnG0fhXSv
y0MYpnuDXFKV5VTMaSaTfty7UTcutdwWrvFhjizaEVVEOj-I-PvjR4z-pIBINQcH-4UJddtaJuTVYXbh08_-ygYy8XbgfYI6mrMDgEJylKYyZxQxBMz4eAie
whbpFNObohiJY_IsUqtCrvXPxAjIt8Kt5n7MtfoQQeIRHGAPm0U1ykx527rnj7Acvd3p6Cjs6d0l8gIDpIYgaFehUumPpRov6DwMHgBlRQogzGnHSvzxSx56
0Vd-I9j_Ce3CCS6fDnU1g1GIhyVbQfSLyLjlKWJfxXbRuvfWuE-zOwyEZvfUeBOaye5t48julVSgA-A9TxpyUmPYDR-kcVAUYTcBT1olcV8UYZbUKexNJ7aF
HRnVzo8o3xSz4rV47D4x79c9Xzukee--WUvY8LRaGw_4bTjJgZCBilyRp_F5zffe23DxjNyI91mDA-Dc3h4YgxTLxmTSg8G9eMy1SVQiQzAOvUylcqXNP9WJ
DJ5J9hC2ItHXraZyNLj561E4ZQmnYRAP85OFW3Ap_Pv4X5huQX33k4XXSQT6x64a4IQZDtx7cJXaLLfhf71p1ro8M04LqvM2YOZ6FGc4rsoOQjsebScPC5Lp
m4HLr4HHaddSxJS2GWAZfaQwceLoLmVWjbdjPs5JaVBX6hteEQVK1DP8d1kPcgkGWLGg6rTfOZfEiGLclH6nAgkdvTbMLioKOEAwHcZv_8f9rvX9YaQ4dnFX
qWP5Of2bRI5koKO_rrcSkp1Rd2Q9xB6jJ3WrKNCgS92TiFnCufnkPZKSttqpjl3cMLksoimiIVYPnIGo8sPVSID4PVKCMfwukva7-ynRpDsxJmDR6flRM4Bn
N1C9jeb7OYOo1n6ylNyp3nVUFaJszOzFm5eR5P68AOYsL5xF9Ha07Ebo1IvSNCNIvur7HjlkhY9s3PAQoSYyS_2oXpJw7pDkZU6YvxPckdlJpi3o4R9qhIKm
5vkr7R6yQJnI-qrN81svUUUeuKTIULdWRCUs-kK9uhxn28b9WdtPl-zR-Brujvr3btCQMGIZm4ghjkTelsbyx0r5-ncSdzhEEoCBl2GbUPFTLAw3gywHraPE
99asCfznitSIo93sbHrdnupJwF19aCxjEYoJUAPFWt0ONO9crsq3yO-WgK4kF4fSjKMutu0YwXUzkUUPyu3VWsiC-jtR47Pkw_uxKDHS3YJ10qSEvVqMh3h6
7oJ38yvj1nZtOCLS-MEFFQ1lpehxEx3oqHlgWEzSjNq2Lkz1iXU8ZxPFm8gEtgORg7K2nJq5zwL4GGxVsmBFmUgjFi3mmKN6Sx18w01thlTVWsbodG8hG7qN
U00pV9u8rty24Ijt077pSIK2fXDmS0SGznyiS4qMMDuEJhWPwNe9vkwDbf6vmG_80zWpC9lUVUyps6VSFQadSC8zwJt0djYysUBTawOVeCVZwUs9X7s0_fWx
F0xq4qJcpZqdVO2JnNj0PjZ-I3cqVPxeK4TCsZuai_U7tFttlF_bl_mF
}
@enduml