@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

AddRelTag("validate", $textColor="orange", $lineColor="Blue", $lineStyle = DashedLine())
AddRelTag("download", $textColor="orange", $lineColor="Blue")


Person(user, "API User")  #Grey

System(trs_cli, "TUF-REPOSITORY-SERVICE-CLI", "Command Line Interface")
System(tuf_repository_service_api, "TUF-REPOSITORY-SERVICE-API", "HTTP Rest API") #LightBlue

Rel_D(user, trs_cli, "Command Line")
Rel_D(trs_cli, tuf_repository_service_api, "HTTP")


HIDE_STEREOTYPE()
@enduml