name: Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: "Build Docs"
      run: |
        apt-get update -y && apt-get install -y plantuml make
        pip install -r requirements-docs.txt
        make docs

