name: Lint

on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'tests/**'
      - 'Pipfile*'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.13'

      - name: Lint
        run: |
          pip install pipenv
          pipenv install -d
          pipenv run make lint